USE [Campus6]

SELECT PROGRAM
	,DEGREE
	,CURRICULUM
	,count(*) [Count]
	,(PROGRAM + '/' + DEGREE + '/' + CURRICULUM) AS [Export]
	,(CP.LONG_DESC + '/' + CD.LONG_DESC + '/' + CC.LONG_DESC) AS [Desc]
FROM ACADEMIC
INNER JOIN CODE_PROGRAM CP
	ON CP.CODE_VALUE_KEY = PROGRAM
INNER JOIN CODE_DEGREE CD
	ON CD.CODE_VALUE_KEY = DEGREE
INNER JOIN CODE_CURRICULUM CC
	ON CC.CODE_VALUE_KEY = CURRICULUM
WHERE ACADEMIC_YEAR >= 2019
	AND ACADEMIC_FLAG = 'y'
	AND CP.[STATUS] = 'A'
	AND CD.[STATUS] = 'A'
	AND CC.[STATUS] = 'A'
	AND APPLICATION_FLAG = 'Y'
GROUP BY PROGRAM
	,DEGREE
	,CURRICULUM
	,CP.LONG_DESC
	,CD.LONG_DESC
	,CC.LONG_DESC
ORDER BY CURRICULUM
	,count(*) DESC
