USE [Campus6]

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


-- =============================================
-- Author:		Wyatt Best
-- Create date: 2016-11-21
-- Description:	Inserts a row into PersonEthnicity. Designed to be called from within MCNY_SlaPowInt_UpdateDemographics
--				The PersonEthnicityId column is automatically generated by Ellucian code.
--				
--				Transaction isn't used because pyodbc automatically wraps transactions. Be careful if running manually!
--
--  2019-10-15	Wyatt Best:	Renamed and moved to [custom] schema.
-- =============================================
CREATE PROCEDURE [custom].[PS_insPersonEthnicity]
	@PersonId int
	,@Opid nvarchar(8)
	,@Today datetime
	,@Now datetime
	,@IpedsFederalCategoryId tinyint
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO PersonEthnicity
	(IpedsFederalCategoryId
	,CREATE_DATE
	,CREATE_TIME
	,CREATE_OPID
	,CREATE_TERMINAL
	,REVISION_DATE
	,REVISION_TIME
	,REVISION_OPID
	,REVISION_TERMINAL
	,PersonId)
	VALUES
	(@IpedsFederalCategoryId
	,@Today
	,@Now
	,@Opid
	,'0001'
	,@Today
	,@Now
	,@Opid
	,'0001'
	,@PersonId)
END
GO
