USE [Campus6];

SELECT CP.LONG_DESC
	,CD.LONG_DESC
	,CC.LONG_DESC
	,CP.CODE_VALUE_KEY
	,CD.CODE_VALUE_KEY
	,CC.CODE_VALUE_KEY
	,ProgramOfStudyId
FROM PROGRAMOFSTUDY POS
LEFT JOIN CODE_PROGRAM CP
	ON CP.ProgramId = POS.Program
LEFT JOIN CODE_DEGREE CD
	ON CD.DegreeId = POS.Degree
LEFT JOIN CODE_CURRICULUM CC
	ON CC.CurriculumId = POS.Curriculum
